stages:
  - deploy

dev:
  stage: deploy
  script:
    - ssh gitlab-deployer@10.20.99.19 "cd /var/www/erp && git pull && composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts && npm i && docker-compose down && docker-compose up --build --detach"
  environment:
    name: dev
    url: http://10.20.99.19
  only:
    - main
