stages:
  - build
  - deploy

composer:
  stage: build
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  artifacts:
    expire_in: 1 month
    paths:
      - vendor/
      - .env
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/

npm:
  stage: build
  script:
    - npm install
    - npm run production

  artifacts:
    expire_in: 1 month
    paths:
      - node_modules/
      - public/css/
      - public/js/
      - public/fonts/
      - public/img/
      - public/mix-manifest.json

  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - node_modules/

dev:
  stage: deploy
  script:
    - base64 -d ${ERP_REMOTE_DEV_ENV} > .env
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr --delete '\r' | ssh-add - > /dev/null
    - mkdir --parents ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan 10.20.99.19 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - rsync --archive --verbose --compress --delete-after ./ gitlab-deployer@10.20.99.19:/var/www/erp
    - ssh gitlab-deployer@10.20.99.19 "cd /var/www/erp && docker-compose down && docker-compose up --build --detach"
  environment:
    name: dev
    url: http://10.20.99.19
  only:
    - main
  dependencies:
    - composer
    - npm
