stages:
  - deploy

variables:
  DEPLOY_SERVER: "gitlab-deployer@10.20.99.19"
  DEPLOY_PATH: "/var/www/erp"
  BRANCH: "main"

before_script:
  - apk add --no-cache openssh-client
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - ssh-keyscan 10.20.99.19 >> ~/.ssh/known_hosts

deploy:
  stage: deploy
  script:
    - ssh $DEPLOY_SERVER "cd $DEPLOY_PATH && git pull origin $BRANCH"
    - ssh $DEPLOY_SERVER "cd $DEPLOY_PATH && composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts"
    - ssh $DEPLOY_SERVER "cd $DEPLOY_PATH && npm i && npm run production"
    - ssh $DEPLOY_SERVER "cd $DEPLOY_PATH && docker-compose down"
    - ssh $DEPLOY_SERVER "cd $DEPLOY_PATH && docker-compose up --build --detach"
  only:
    - main
