stages:
  - build

composer:
  stage: build
  script:
      - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - cp .env.example .env
      - php artisan key:generate
  artifacts:
    expire_in: 1 month
    paths:
      - vendor/
      - .env
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/

#npm:
#  stage: build
#  script:
#      - npm install
#      - npm run production
#
#  artifacts:
#    expire_in: 1 month
#    paths:
#      - node_modules/
#      - public/css/
#      - public/js/
      
#  cache:
#    key: ${CI_COMMIT_REF_SLUG}-npm
#    paths:
#      - node_modules/

