stages:
  - build
  - deploy

variables:
  BRANCH: $CI_COMMIT_REF_NAME

composer:
  stage: build
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  artifacts:
    expire_in: 1 month
    paths:
      - vendor/
      - .env
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/

npm:
  stage: build
  script:
    - npm install
    - npm run build

  artifacts:
    expire_in: 1 month
    paths:
      - node_modules/
      - public/css/
      - public/js/
      - public/fonts/
      - public/img/
      - public/mix-manifest.json

  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - node_modules/


deploy_stage:
  variables:
    DEPLOY_SERVER: "gitlab-deployer@10.20.99.19"
    DEPLOY_ADDRESS: "10.20.99.19"
    DEPLOY_PATH: "/var/www/erp"
  stage: deploy
  before_script:
    - base64 -d ${ERP_REMOTE_DEV_ENV} > .env
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr --delete '\r' | ssh-add - > /dev/null
    - mkdir --parents ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan 10.20.99.19 >> ~/.ssh/known_hosts || (echo "ssh-keyscan failed" && exit 1)
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh $DEPLOY_SERVER "cd $DEPLOY_PATH && git pull http://gitlab-ci-token:$GITLAB_TOKEN@10.20.99.20:8080/dev/erp.git $BRANCH"
    - ssh $DEPLOY_SERVER "cd $DEPLOY_PATH && composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts"
    - ssh $DEPLOY_SERVER "cd $DEPLOY_PATH && npm i && npm run production"
    - ssh $DEPLOY_SERVER "cd $DEPLOY_PATH && docker-compose down"
    - ssh $DEPLOY_SERVER "cd $DEPLOY_PATH && docker-compose up --build --detach"
  only:
    - main

deploy_dev:
  variables:
    DEPLOY_SERVER: "gitlab-deployer@10.20.99.17"
    DEPLOY_ADDRESS: "10.20.99.17"
    DEPLOY_PATH: "/var/www/dev.erp.sk-gorod.com"
  stage: deploy
  before_script:
    - base64 -d ${ERP_REMOTE_DEV_ENV} > .env
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr --delete '\r' | ssh-add - > /dev/null
    - mkdir --parents ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan 10.20.99.17 >> ~/.ssh/known_hosts || (echo "ssh-keyscan failed" && exit 1)
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh $DEPLOY_SERVER "cd $DEPLOY_PATH && git pull http://gitlab-ci-token:$GITLAB_TOKEN@10.20.99.20:8080/dev/erp.git $BRANCH"
    - ssh $DEPLOY_SERVER "cd $DEPLOY_PATH && composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts"
    - ssh $DEPLOY_SERVER "cd $DEPLOY_PATH && npm i && npm run production"
    - ssh $DEPLOY_SERVER "cd $DEPLOY_PATH && docker-compose down"
    - ssh $DEPLOY_SERVER "cd $DEPLOY_PATH && docker-compose up --build --detach"
  only:
    - dev

