stages:
  - deploy

variables:
  DEPLOY_SERVER: "gitlab-deployer@10.20.99.19"
  DEPLOY_PATH: "/var/www/erp"
  BRANCH: "main"

before_script:
  - base64 -d ${ERP_REMOTE_DEV_ENV} > .env
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr --delete '\r' | ssh-add - > /dev/null
  - mkdir --parents ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan 10.20.99.19 >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

deploy:
  stage: deploy
  script:
    - ssh $DEPLOY_SERVER "cd $DEPLOY_PATH && git pull http://gitlab-ci-token:$GITLAB_TOKEN@10.20.99.20:8080/dev/erp.git $BRANCH"
    - ssh $DEPLOY_SERVER "cd $DEPLOY_PATH && composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts"
    - ssh $DEPLOY_SERVER "cd $DEPLOY_PATH && npm i && npm run production"
    - ssh $DEPLOY_SERVER "cd $DEPLOY_PATH && docker-compose down"
    - ssh $DEPLOY_SERVER "cd $DEPLOY_PATH && docker-compose up --build --detach"
  only:
    - main
