version: "3.8"

services:

  #php service
  erp_app:
    container_name: erp_app
    build:
      context: ./docker
      dockerfile: Dockerfile
      target: php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "80:80"
    environment:
      - VIRTUAL_HOST=dev.erp.sk-gorod.com
      - LETSENCRYPT_HOST=dev.erp.sk-gorod.com
      - LETSENCRYPT_EMAIL=dev@sk-gorod.com
    depends_on:
      - erp_database

  erp_redis:
    image: 'redis:alpine'
    container_name: erp_redis
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'sail-redis:/data'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'

  #Database service
  erp_database:
    container_name: erp_database
    restart: always
    image: mariadb:11.4.2-ubi
    ports:
      - "3306:3306"
    environment:
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - erp-database-data:/var/lib/mysql

  phpmyadmin:
    build: ./docker/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=${PMA_USER}
      - MYSQL_PASSWORD=${PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}
      - MAX_EXECUTION_TIME=${PMA_MAX_EXECUTION_TIME}
      - MEMORY_LIMIT=${PMA_MEMORY_LIMIT}
      - UPLOAD_LIMIT=${PMA_UPLOAD_LIMIT}
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - erp_database
volumes:
  erp-database-data: ~
  sail-redis:
    driver: local
